/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIStarter */

#ifndef _Included_JNIStarter
#define _Included_JNIStarter
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     JNIStarter
 * Method:    Negative
 * Signature: ([I[I[III)V
 */
JNIEXPORT void JNICALL Java_serverSide_Filters_JNI_JNIStarter_Negative
  (JNIEnv *, jobject, jintArray, jint);


/*
 * Class:     JNIStarter
 * Method:    Binary
 * Signature: ([I[I[IIII)V
 */
JNIEXPORT void JNICALL Java_serverSide_Filters_JNI_JNIStarter_Binary
  (JNIEnv *, jobject, jintArray,jint, jint);

/*
 * Class:     JNIStarter
 * Method:    Logarithmic
 * Signature: ([I[I[III)V
 */
JNIEXPORT void JNICALL Java_serverSide_Filters_JNI_JNIStarter_Logarithmic
  (JNIEnv *, jobject, jintArray,jint, jint, jint);



/*
 * Class:     JNIStarter
 * Method:    Gamma
 * Signature: ([I[I[III)V
 */
JNIEXPORT void JNICALL Java_serverSide_Filters_JNI_JNIStarter_Gamma
  (JNIEnv *, jobject, jintArray,jint, jint, jint);


/*
 * Class:     JNIStarter
 * Method:    ChannelSplit
 * Signature: ([I[I[IIII)V
 */
JNIEXPORT void JNICALL Java_serverSide_Filters_JNI_JNIStarter_ChannelSplit
  (JNIEnv *, jobject, jintArray, jintArray, jintArray, jint, jint, jint);


/*
 * Class:     JNIStarter
 * Method:    GrayScale
 * Signature: ([I[I[III)V
 */
JNIEXPORT void JNICALL Java_serverSide_Filters_JNI_JNIStarter_GrayScale
  (JNIEnv *, jobject, jintArray, jintArray, jintArray, jint);

//BORDER

/*
 * Class:     JNIStarter
 * Method:    HighPass
 * Signature: ([I[I[III)V
 */
JNIEXPORT void JNICALL Java_serverSide_Filters_JNI_JNIStarter_HighPass
  (JNIEnv *, jobject, jintArray, jintArray, jintArray, jint, jint);

/*
 * Class:     JNIStarter
 * Method:    Laplaciano
 * Signature: ([I[I[III)V
 */
JNIEXPORT void JNICALL Java_serverSide_Filters_JNI_JNIStarter_Laplaciano
  (JNIEnv *, jobject, jintArray, jintArray, jintArray, jint, jint);

/*
 * Class:     JNIStarter
 * Method:    Media
 * Signature: ([I[I[III)V
 */
JNIEXPORT void JNICALL Java_serverSide_Filters_JNI_JNIStarter_Media
  (JNIEnv *, jobject, jintArray, jintArray, jintArray, jint, jint);

/*
 * Class:     JNIStarter
 * Method:    Median
 * Signature: ([I[I[III)V
 */
JNIEXPORT void JNICALL Java_serverSide_Filters_JNI_JNIStarter_Median
  (JNIEnv *, jobject, jintArray, jintArray, jintArray, jint, jint);

/*
 * Class:     JNIStarter
 * Method:    Prewitt
 * Signature: ([I[I[III)V
 */
JNIEXPORT void JNICALL Java_serverSide_Filters_JNI_JNIStarter_Prewitt
  (JNIEnv *, jobject, jintArray, jintArray, jintArray, jint, jint);

/*
 * Class:     JNIStarter
 * Method:    Roberts
 * Signature: ([I[I[III)V
 */
JNIEXPORT void JNICALL Java_serverSide_Filters_JNI_JNIStarter_Roberts
  (JNIEnv *, jobject, jintArray, jintArray, jintArray, jint, jint);

/*
 * Class:     JNIStarter
 * Method:    Sobel
 * Signature: ([I[I[III)V
 */
JNIEXPORT void JNICALL Java_serverSide_Filters_JNI_JNIStarter_Sobel
  (JNIEnv *, jobject, jintArray, jintArray, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
